version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--experimental.localPlugins.maintenance.moduleName=github.com/programic/traefik-maintenance-plugin"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    networks:
      - web

  nginx:
    image: nginx:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.test`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./nginx:/usr/share/nginx/html

networks:
  web:
    driver: bridge
